from typing import Protocol

from brew.aiden.schedules.model.schedule import Schedule, ScheduleCreate, ScheduleUpdate


class ScheduleFacade(Protocol):
    async def get_schedules(self) -> list[Schedule]: ...
    async def create_schedule(self, schedule: ScheduleCreate) -> Schedule: ...
    async def update_schedule(self, schedule_id: str, schedule: ScheduleUpdate) -> None: ...
    async def delete_schedule(self, schedule_id: str) -> None: ...
