from typing import Protocol

from brew.aiden.profiles.model.profile import Profile, ProfileCreate, ProfileLink, ProfileUpdate


class ProfileFacade(Protocol):
    async def get_profiles(self) -> list[Profile]: ...
    async def get_profile(self, profile_id: str) -> Profile | None: ...
    async def create_profile(self, profile: ProfileCreate) -> Profile: ...
    async def create_profile_from_link(self, brew_link: str) -> Profile: ...
    async def update_profile(self, profile_id: str, profile: ProfileUpdate) -> None: ...
    async def delete_profile(self, profile_id: str) -> None: ...
    async def generate_link(self, profile_id: str) -> ProfileLink: ...
